### ISSUE TITLE
set tab width for listings

### ISSUE THREAD

**Issue by AllTradesz** [nodejs/node-inspect#105]
Hello. Is there any way to have the debugger show tabs with something other than the standard 8 spaces? Would make for much more readable listings for me  👍

**Comment by hybrist** [comment]
Since the debugger prints to the terminal, this is likely more a terminal feature than a debugger feature. You can potentially change the tab width for interactive shells using `tabs`: https://askubuntu.com/questions/63424/how-to-change-tab-width-in-terminal-in-ubuntu-10-04

If anybody wants to send a pull request to add a special option (environment variable maybe?), the code for `node-inspect` has been moved to the main nodejs/node repository.
