### ISSUE TITLE
Failures on win10

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-inspect#22]
From initial CI runs:

https://ci.nodejs.org/view/x%20-%20Diagnostics/job/node-inspect-continuous-integration/MACHINE=win10/5/

```
error:                     | not ok 9 - test/cli/preserve-breaks.test.js # time=1181.441ms  
verbose:                                                   | not ok 1 - stepping through breakpoints #
verbose: 57d5f0d5f0e10143926cda9da0f3ba058fa7c2d9 npm-test:| not ok 2 - test/cli/break.test.js #
verbose:                                                   | not ok 6 - marks the 3nd    
verbose: 57d5f0d5f0e10143926cda9da0f3ba058fa7c2d9 npm-test:| not ok 8 - should match pattern
verbose:                                                   | not ok 1 - run after quit / restart #      
```

**Comment by joshgav** [comment]
cc @nodejs/platform-windows @joaocgreis @bzoz can you take a look? Thanks!

**Comment by jkrems** [comment]
Any update on this front? I can try to fire up win10 but I'd definitely be on the slower side for this investigation.

**Comment by joaocgreis** [comment]
I investigated `test/cli/break.test.js` and `test/cli/exec.test.js` and found it to be a race condition.

The machines that run Windows 10 in CI are all single-processor. For Windows 2012, only 3 out of the 15 machines are single-processor. This makes timing issues stand out, and has already helped finding problems in node core before. I can reproduce on a local Windows 10 VM when I set it to 1 processor, but not when I set it to more.

For `test/cli/break.test.js`, what happens when it fails in https://github.com/nodejs/node-inspect/blob/df182d9942300ec9704c26f0ec06a5b18630a04d/test/cli/break.test.js#L46-L49 is that `cli.output` is set to
```
break in examples\break.js:3
debug> 
```
instead of 
```
break in examples\break.js:3
  1 (function (exports, require, module, __filename, __dirname) { const x = 10;
  2 let name = 'World';
> 3 name = 'Robin';
  4 function sayHello() {
  5   if (x > 0) {
```
as the test expects. The issue with `test/cli/exec.test.js` is similar.

**Comment by jkrems** [comment]
I think this specific issue (split break output) is fixed by https://github.com/nodejs/node-inspect/pull/34/commits/2b93173d95e7f8b30d85603613cb2ae3b3ec18db.

**Comment by jkrems** [comment]
The last thing I can't figure out right now is why the "set breakpoint before loading a file" isn't passing on win10: https://ci.nodejs.org/view/x%20-%20Diagnostics/job/node-inspect-continuous-integration/17/MACHINE=win10/console. It seems to just run past that line.

**Comment by jkrems** [comment]
Should be fixed on latest master.
