### ISSUE TITLE
Failures on zLinux

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-inspect#23]
From initial CI runs:
https://ci.nodejs.org/view/x%20-%20Diagnostics/job/node-inspect-continuous-integration/MACHINE=rhel72-s390x/5/

```
verbose: 57d5f0d5f0e10143926cda9da0f3ba058fa7c2d9 npm-test:| not ok 5 - Error: Timeout (2000) while waiting for /(?:assert|break|debugCommand|exception|other|promiseRejection) in/; found: < Starting inspector on 127.0.0.1:9229 failed: address already in use debug>
verbose:                                                   | not ok 1 - break on (uncaught) exceptions # time=2599.453ms
verbose: 57d5f0d5f0e10143926cda9da0f3ba058fa7c2d9 npm-test:| not ok 3 - test/cli/exceptions.test.js # time=3289.24ms


```

**Comment by CurryKitten** [comment]
I've run this in the same way as in CI on a zLinux64 rhel7 machine I've replicated the failure twice in approx 30 runs (otherwise passing all the tests)

It looks like a timing problem - perhaps on more loaded machines.  The restart command in the debugger - that runs before failure in CI - looks like it makes the debugger rebind to it's default 9229 port.  Perhaps possible that the port is still in TIME_WAIT when the bind request happens and fails just before the final ACK arrives back and closes the connection down cleanly.

**Comment by jkrems** [comment]
The latest master is all green.
