### ISSUE TITLE
Feature request for CLI debugger: Disable "break on start"

### ISSUE THREAD

**Issue by joeflack4** [nodejs/node-inspect#65]
* **Version**:
v9.5.0
* **Platform**:
Darwin joe.sph.ad.jhsph.edu 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
* **Subsystem**:
OS X?

## Desired CLI command
Something like: `node inspect PATH/TO/FILE --break-on-breakpoints-only`

## Current behavior
`node inspect PATH/TO/FILE` results in:
> ...
> Break on start in PATH/TO/FILE:1
> ...

## Desired behavior
`node inspect PATH/TO/FILE --break-on-breakpoints-only` would result in:
> ...
> Breaking on in PATH/TO/FILE:X
> ...
...where "X" corresponds to the line number in the file where `debugger;` first appears.

## References
- [Previous request](https://github.com/nodejs/node-v0.x-archive/issues/5438)
- [Stackoverflow](https://stackoverflow.com/questions/16420374/how-to-disable-in-the-node-debugger-break-on-first-line)

**Comment by bag-man** [comment]
Any updates on this?

**Comment by jkrems** [comment]
@bag-man I don't think anybody is actively working on this unfortunately.

**Comment by Bogidon** [comment]
I get that break on start might be useful in certain situations*, but no other debugger I've ever used works this way so in it's dissimilarity it's a feature that further complicates debugging in Node.

Node feels to me like the platform most indifferent to existing (e.g. UNIX) standards and likes inventing it's own ways of doing things. I don't see this as a good thing. The debugger is key among my frustrations of this type.

*it seems mostly useful if you are working on Node itself(?)

---

Please don't take this as a random criticism, I'm only trying to communicate my viewpoint. If someone wants to point me in a direction towards contributing on something that aligns with my viewpoint of making the Node debugger feel more "standard" please do.

**Comment by eugeneo** [comment]
All CLI debuggers need to break early to give the user a chance to setup breakpoints. E.g. in GDB you would start, load the executable, set breakpoints then run. Sometimes this may be annoying, and the way to deal with it in GDB is to autoexecute commands on load. Maybe, node-inspect could do the same, provide a way to supply a script that would be executed on start? Then user can simply run node-inspect with “continue”

**Comment by bag-man** [comment]
I always set breakpoints with a debugger statement in the actual code, so I never need it to break on start. 

I think a good cli debugger for node would be really cool to have, and it's certainly possible to make. I think the problem is most node developers use the chrome inspector for their debugging porpoises :dolphin:, so it's never going to happen unless we make it ourselves.

**Comment by jkrems** [comment]
Yeah, I personally use vscode or Chrome Devtools as my primary debug client. `node inspect` (like `node debug` before it) is effectively in maintenance mode. Nobody is actively trying to push it forward since nobody seems to both use it and have time to contribute to its evolution.

> it seems mostly useful if you are working on Node itself(?)

I think this is trying to rationalize too much. I'm pretty sure that the current behavior is the consequence of two things:

1. It was the easiest way to implement the `lldb` / other CLI debugger flow of "start CLI debugger, configure / set breakpoints, run program" when the very first version of `node debug` was written.
2. Since then, the CLI debugger has consistently been something that was considered too important to remove but at the same time it was never used widely enough to motivate somebody to work on its UX.

For working on node itself, the CLI debugger isn't really useful because it can't capture C++ calls and it's not integrated with any editor. The only place that has been brought up consistently where people use it, is in environments where people have to debug a program on a locked-down production system that doesn't allow installation of additional tools or exposing any ports.

**Comment by Bogidon** [comment]
I guess the issue here is that Node didn't spawn the Javascript development environment since V8 and other engines were built before Node, which led to an atypical debugging setup. I feel like the debugging setup has snowballing effects that prevents Javascript from being maybe as useful as it could be outside of web development. Anyway I guess right tool <> right job, all that.
